version: '3.4'

services:
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - /volumes/mongodb:/data/db
    container_name: mongodb_imagens

  s3ninja:
    image: kcomlabs/s3ninja
    ports:
      - "9444:9444"
    container_name: s3_imagens

  rabbitMQ:
    image: rabbitmq:3.7.7-management
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "HFEWIFHWIUEGHI"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbit_imagnes